name: econ833-env
channels:
- conda-forge
dependencies:
- python>=3.9, <3.13
- numpy
- ipython
- scipy>=1.7.1
- pandas>=1.2.5
- numba
- jax
- matplotlib
- scikit-learn
- dask>=2.30.0
- dask-core>=2.30.0
- distributed>=2.30.1
- paramtools>=0.15.0
- sphinx>=3.5.4
- sphinx-argparse
- sphinxcontrib-bibtex>=2.0.0
- sphinx-math-dollar
- pydata-sphinx-theme
- jupyter-book>=0.11.3
- jupyter
- pytest>=6.0
- pytest-cov
- pytest-xdist
- pylint
- coverage
- requests
- openpyxl>=3.1.2
- xlrd
- black>=24.1.1
- statsmodels
- linearmodels
- tensorflow
- pip
- pip:
  - pygam
  - linecheck
  - memory-profiler
  - plotly-express
  - pyreadstat
  - tables
  - paramtools
  - taxcalc
  - ogcore
  - regpyhdfe
  - FixedEffectModelPyHDFE
  - stargazer
  - rdd